export const metadata = {
  title: "Terms of Service — Aurum Tarot",
  description:
    "Terms of service for Aurum Tarot. Subscriptions, AI content, liability, and your rights.",
};

export default function TarotTerms() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-20 text-neutral-200">
      <h1 className="mb-4 text-4xl font-bold text-white">
        Terms of Service / Nutzungsbedingungen
      </h1>
      <p className="mb-2 text-lg text-neutral-300">Aurum Tarot</p>
      <p className="mb-10 text-sm text-neutral-500">
        Last updated: June 20, 2026
      </p>

      <p className="mb-6">
        These Terms of Service (&quot;Terms&quot;) govern your use of the
        Aurum Tarot application (&quot;the App&quot;) published by Eduard
        Bruch. By downloading, installing, or using the App, you agree to
        these Terms.
      </p>

      {/* 1. Entertainment Disclaimer */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        1. Entertainment Disclaimer
      </h2>
      <p className="mb-6 border-l-4 border-indigo-500 pl-4 text-neutral-100">
        All content in the App &mdash; including tarot readings, card
        meanings, AI-generated interpretations, and all other spiritual or
        esoteric content &mdash; is provided for{" "}
        <strong>
          entertainment and self-reflection purposes only
        </strong>
        . It does not constitute medical, health, psychological, legal, or
        financial advice. You should not make important life decisions based
        solely on content provided by the App. Always consult qualified
        professionals for medical, legal, financial, or psychological matters.
      </p>

      {/* 2. Subscriptions */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        2. Subscriptions and Payments
      </h2>
      <p className="mb-4">
        Aurum Tarot offers premium features through auto-renewable
        subscriptions (weekly and yearly plans).
      </p>
      <ul className="mb-4 list-disc pl-6 space-y-2">
        <li>
          Payment will be charged to your Apple ID account at confirmation of
          purchase.
        </li>
        <li>
          Subscription automatically renews unless canceled at least 24 hours
          before the end of the current period.
        </li>
        <li>
          Your account will be charged for renewal within 24 hours prior to
          the end of the current period at the rate of the selected plan.
        </li>
        <li>
          You can manage and cancel your subscriptions by going to your
          account settings on the App Store after purchase.
        </li>
        <li>
          Any unused portion of a free trial period, if offered, will be
          forfeited when you purchase a subscription.
        </li>
      </ul>
      <p className="mb-6">
        Your statutory right of withdrawal for digital content is handled
        through Apple&apos;s refund process in accordance with Apple&apos;s
        Media Services Terms and Conditions and applicable consumer
        protection law.
      </p>

      {/* 3. AI-Generated Content */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        3. AI-Generated Content
      </h2>
      <p className="mb-4">
        Aurum Tarot offers optional AI-powered tarot interpretations as a
        premium feature. These interpretations are generated by a third-party
        AI service provider and are provided for entertainment purposes only.
      </p>
      <p className="mb-6">
        We do not guarantee the accuracy, completeness, or usefulness of
        AI-generated content. AI interpretations should not be relied upon
        for medical, psychological, legal, or financial decisions. By using
        the AI interpretation feature, you consent to your card data and
        questions being processed as described in our{" "}
        <a
          href="/tarot/privacy"
          className="text-indigo-400 underline"
        >
          Privacy Policy
        </a>
        .
      </p>

      {/* 4. Intellectual Property */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        4. Intellectual Property
      </h2>
      <p className="mb-6">
        All content, designs, graphics, card artwork, text, and software in
        the App are the intellectual property of Eduard Bruch or their
        respective licensors and are protected by copyright and other
        intellectual property laws. You may not reproduce, distribute, modify,
        or create derivative works from any content in the App without prior
        written consent.
      </p>

      {/* 5. User Conduct */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        5. User Conduct
      </h2>
      <p className="mb-6">
        You agree to use the App only for lawful purposes and in accordance
        with these Terms. You may not use the App in any manner that could
        damage, disable, overburden, or impair the service, or attempt to
        reverse-engineer, decompile, or tamper with any part of the App.
      </p>

      {/* 6. Limitation of Liability */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        6. Limitation of Liability
      </h2>
      <p className="mb-6">
        To the maximum extent permitted by applicable law, Eduard Bruch shall
        not be liable for any indirect, incidental, special, consequential, or
        punitive damages, or any loss of profits or revenues, whether incurred
        directly or indirectly, or any loss of data, use, goodwill, or other
        intangible losses, resulting from (a) your use of or inability to use
        the App; (b) any content obtained from the App, including
        AI-generated interpretations; or (c) unauthorized access to or
        alteration of your data. This limitation of liability does not apply
        to liability for intent (Vorsatz) or gross negligence (grobe
        Fahrl&auml;ssigkeit), or where mandatory liability under German law
        applies (e.g., under the Produkthaftungsgesetz).
      </p>

      {/* 7. Disclaimer of Warranties */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        7. Disclaimer of Warranties
      </h2>
      <p className="mb-6">
        The App is provided &quot;as is&quot; and &quot;as available&quot;
        without warranties of any kind, either express or implied, including
        but not limited to implied warranties of merchantability, fitness for
        a particular purpose, and non-infringement. We do not warrant that
        the App will be uninterrupted, secure, or error-free. This does not
        affect your statutory warranty rights (gesetzliche
        Gew&auml;hrleistungsrechte) under German law.
      </p>

      {/* 8. Governing Law */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        8. Governing Law and Jurisdiction
      </h2>
      <p className="mb-6">
        These Terms are governed by the laws of the Federal Republic of
        Germany, excluding the UN Convention on Contracts for the
        International Sale of Goods (CISG). If you are a consumer within the
        European Union, you also enjoy the protection of the mandatory
        provisions of consumer protection law in your country of residence.
        The place of jurisdiction is Hamburg, Germany, except where mandatory
        consumer protection law provides otherwise.
      </p>

      {/* 9. Online Dispute Resolution */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        9. Online Dispute Resolution
      </h2>
      <p className="mb-6">
        The European Commission provides an online dispute resolution platform
        at{" "}
        <a
          href="https://ec.europa.eu/consumers/odr"
          className="text-indigo-400 underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          https://ec.europa.eu/consumers/odr
        </a>
        . We are neither obligated nor willing to participate in dispute
        resolution proceedings before a consumer arbitration board.
      </p>

      {/* 10. Changes */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        10. Changes to These Terms
      </h2>
      <p className="mb-6">
        We may update these Terms from time to time. For material changes, we
        will notify you in the app and request your renewed consent where
        required by applicable law. Continued use of the App after
        non-material changes constitutes acceptance of the updated Terms.
      </p>

      {/* 11. Contact */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        11. Contact
      </h2>
      <p>
        For questions about these Terms, contact:{" "}
        <a
          href="mailto:support@eduardbruch.com"
          className="text-indigo-400 underline"
        >
          support@eduardbruch.com
        </a>
      </p>
    </main>
  );
}
