import type { NextConfig } from "next";
import stashRedirects from "./stash-redirects.json";
import sounddialRedirects from "./sounddial-redirects.json";
import opticJettyRedirects from "./optic-jetty-redirects.json";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Stash moved to stashphotovault.com: 301s for /vault pages whose new page exists.
      // Generated by stash-site/scripts/stash_redirect_map.py; see docs/STASH_REDIRECTS.md.
      // Must stay first (one hop) and stay forever: the shipped app opens /vault/privacy and /vault/terms.
      ...(stashRedirects as { source: string; destination: string; statusCode: 301 }[]),
      {
        source: "/vault/blog/:locale/best-apps-to-hide-photos-2026",
        destination:
          "/vault/blog/:locale/best-secret-photo-vault-apps-iphone",
        permanent: true,
      },
      // SoundDial moved to sounddial.eu: 301s only for old URLs whose new page exists (static rules first,
      // then one rule per destination with a locale list; no two rules match the same path).
      // Generated by sounddial-site/scripts/redirect-status.mjs (docs/redirects.ready.next.json); see
      // sounddial-site/docs/REDIRECT_WIRING.md. Keep forever: the shipped app opens /sounddial/privacy and /sounddial/terms.
      ...(sounddialRedirects as { source: string; destination: string; statusCode: 301 }[]),
      // Optic moved to opticocr.eu and Jetty to jettydock.eu (2026-10-10): slugs unchanged, every locale goes to the
      // English article (no translations on the new sites yet). Maps + 200-checks: seo-toolbox/apps/{optic,jetty}/redirect_map.csv.
      // /optic/terms stays on the hub (no terms page on opticocr.eu). Keep /jetty/privacy|terms forever (App Store links).
      ...(opticJettyRedirects as { source: string; destination: string; statusCode: 301 }[]),
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        ],
      },
    ];
  },
};

export default nextConfig;
