import type { ArticleSet } from "./index";

export const ptArticles: ArticleSet = {
  "how-to-check-cpu-temperature-on-mac": {
    slug: "how-to-check-cpu-temperature-on-mac",
    title: "Como verificar a temperatura da CPU no Mac (Guia 2026)",
    description: "Aprenda todos os métodos para monitorar a temperatura do processador do seu Mac — desde comandos do Terminal até aplicativos de terceiros. Cobre Apple Silicon e Intel.",
    date: "2026-04-02",
    content: `<p>A temperatura da CPU do seu Mac é uma das métricas mais importantes para monitorar. Um processador superaquecido leva ao throttling térmico, desempenho reduzido e vida útil mais curta do hardware. O macOS não inclui uma leitura de temperatura integrada, então aqui estão os métodos confiáveis para verificar a temperatura da CPU em 2026.</p><h2>Por que a temperatura da CPU importa</h2><p>Processadores modernos operam dentro de uma envoltória térmica específica. Quando a CPU excede essa envoltória, o sistema reduz a velocidade do clock — <strong>throttling térmico</strong>. Monitorar a temperatura também ajuda a detectar problemas cedo.</p><h2>Faixas normais de temperatura</h2><ul><li><strong>Repouso:</strong> 35–55 °C (Apple Silicon), 40–60 °C (Intel).</li><li><strong>Carga moderada:</strong> 60–80 °C (Apple Silicon), 65–85 °C (Intel).</li><li><strong>Carga pesada:</strong> 80–100 °C (Apple Silicon), 85–100 °C (Intel).</li></ul><h2>Método 1: Terminal com powermetrics</h2><p><strong>sudo powermetrics --samplers smc -i 1000 -n 1</strong></p><h2>Método 2: Apps de barra de menus</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> exibe temperatura da CPU, GPU, sensores, ventoinhas, carga CPU, pressão de memória, velocidade de rede e saúde da bateria em widgets compactos na barra de menus.</p><h2>O que fazer se o Mac está quente</h2><ol><li>Verificar o Monitor de Atividade.</li><li>Fechar abas e apps desnecessários.</li><li>Garantir circulação de ar.</li><li>Limpar ventoinhas.</li></ol><h2>Resumo</h2><p>Verificar a temperatura da CPU é simples com ferramentas como <a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>. Monitoramento regular ajuda a detectar problemas cedo e prolongar a vida útil do hardware.</p>`,
  },
  "what-is-memory-pressure-on-mac": {
    slug: "what-is-memory-pressure-on-mac",
    title: "O que é pressão de memória no Mac e por que importa",
    description: "Entenda a pressão de memória do macOS — níveis verde, amarelo e vermelho — e como o Mac gerencia RAM com memória comprimida, cabeada e de aplicativos.",
    date: "2026-04-02",
    content: `<p>A pressão de memória é uma métrica composta que reflete quanta demanda está sendo colocada na RAM física do seu Mac. Ela é exibida como um gráfico colorido no Monitor de Atividade.</p><h2>Pressão de memória explicada</h2><ul><li><strong>Verde:</strong> Muita memória disponível. Estado ideal.</li><li><strong>Amarelo:</strong> Recursos de memória ficando restritos. macOS comprime ativamente e pode começar a usar swap.</li><li><strong>Vermelho:</strong> Pressão severa. Swap intensivo, possível encerramento de processos.</li></ul><h2>Como o macOS gerencia a memória</h2><p>O macOS usa memória de aplicativo, memória cabeada, memória comprimida, arquivos em cache e swap. A quantidade de memória "usada" não correlaciona diretamente com a pressão.</p><h2>Monitoramento com apps de barra de menus</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> exibe a pressão de memória diretamente na barra de menus como indicador colorido.</p><h2>Quanta RAM você precisa</h2><ul><li><strong>8 GB:</strong> Uso leve.</li><li><strong>16 GB:</strong> Ideal para a maioria.</li><li><strong>24–32 GB:</strong> Workflows profissionais.</li><li><strong>64–192 GB:</strong> Cargas especializadas.</li></ul><h2>Resumo</h2><p>Pressão de memória é a métrica de memória mais importante no macOS. Ferramentas como <a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> facilitam esse monitoramento.</p>`,
  },
  "best-system-monitor-apps-for-mac": {
    slug: "best-system-monitor-apps-for-mac",
    title: "Melhores apps de monitor de sistema para Mac em 2026",
    description: "Compare os melhores monitores de sistema Mac — iStat Menus, Stats, MenuMeters, TG Pro e Pulse. Recursos, preços e prós e contras honestos.",
    date: "2026-04-02",
    content: `<p>Nesta comparação completa, avaliamos os cinco monitores de sistema Mac mais populares em 2026.</p><h2>iStat Menus</h2><p>O monitor mais estabelecido. Personalização profunda. $11,99.</p><h2>Stats</h2><p>Gratuito e open source. Cobre o essencial.</p><h2>MenuMeters</h2><p>Apenas CPU, memória, disco e rede. Extremamente leve.</p><h2>TG Pro</h2><p>Especialista em temperatura e controle de ventoinhas. $20.</p><h2>Pulse</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> oferece cobertura completa por $5,99 com interface SwiftUI moderna no Mac App Store.</p><table><tr><th>Recurso</th><th>iStat Menus</th><th>Stats</th><th>MenuMeters</th><th>TG Pro</th><th>Pulse</th></tr><tr><td>CPU</td><td>Sim</td><td>Sim</td><td>Sim</td><td>Básico</td><td>Sim</td></tr><tr><td>Pressão memória</td><td>Sim</td><td>Sim</td><td>Básico</td><td>Não</td><td>Sim</td></tr><tr><td>Mac App Store</td><td>Não</td><td>Não</td><td>Não</td><td>Não</td><td>Sim</td></tr><tr><td>Preço</td><td>$11,99</td><td>Grátis</td><td>Grátis</td><td>$20</td><td>$5,99</td></tr></table><h2>Resumo</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> oferece o melhor custo-benefício para monitoramento completo.</p>`,
  },
  "how-to-monitor-network-speed-on-mac": {
    slug: "how-to-monitor-network-speed-on-mac",
    title: "Como monitorar a velocidade de rede no Mac em tempo real",
    description: "Aprenda a rastrear velocidades de upload e download no seu Mac usando Monitor de Atividade, Terminal e apps de barra de menus.",
    date: "2026-04-02",
    content: `<p>Conhecer a velocidade de rede em tempo real do seu Mac é útil para downloads, videochamadas e solução de problemas.</p><h2>Monitor de Atividade</h2><p>Aba Rede: Dados recebidos/s e Dados enviados/s.</p><h2>Terminal</h2><p><strong>nettop</strong> para vista em tempo real. <strong>speedtest-cli</strong> para teste pontual.</p><h2>Apps de barra de menus</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> mostra velocidade upload/download em tempo real na barra de menus.</p><h2>Solução de problemas</h2><ol><li>Executar teste de velocidade.</li><li>Verificar sinal Wi-Fi.</li><li>Identificar consumidores de banda com <a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>.</li><li>Mudar para Ethernet.</li><li>Alterar servidores DNS.</li></ol><h2>Resumo</h2><p>Monitorar a velocidade de rede em tempo real ajuda a entender sua conexão e resolver problemas eficientemente.</p>`,
  },
  "mac-running-slow-how-to-fix": {
    slug: "mac-running-slow-how-to-fix",
    title: "Mac lento? Como diagnosticar e corrigir problemas de desempenho",
    description: "Um guia sistemático para descobrir por que seu Mac está lento. Aprenda a distinguir gargalos de CPU, memória e disco.",
    date: "2026-04-02",
    content: `<p>Um Mac lento pode ter muitas causas diferentes. O diagnóstico correto é essencial.</p><h2>Identificar o tipo de gargalo</h2><ul><li><strong>CPU:</strong> Processador no máximo.</li><li><strong>Memória:</strong> RAM insuficiente.</li><li><strong>Disco:</strong> Armazenamento quase cheio.</li><li><strong>Rede:</strong> Internet lenta.</li></ul><h2>Monitor de Atividade</h2><p>Verifique as abas CPU, Memória e Disco.</p><h2>Monitor de barra de menus</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> mantém métricas sempre visíveis.</p><h2>Corrigir problemas de CPU</h2><ol><li>Encerrar processos problemáticos.</li><li>Atualizar apps.</li><li>Reduzir abas do navegador.</li></ol><h2>Corrigir problemas de memória</h2><ol><li>Fechar apps com alto consumo.</li><li>Reiniciar o Mac.</li><li>Aumentar RAM se possível.</li></ol><h2>Resumo</h2><p>Use o Monitor de Atividade e <a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> para diagnóstico e monitoramento contínuo.</p>`,
  },
  "how-to-check-battery-health-on-mac": {
    slug: "how-to-check-battery-health-on-mac",
    title: "Como verificar a saúde da bateria no MacBook: Guia completo",
    description: "Todos os métodos para verificar a saúde da bateria do seu MacBook — Ajustes do Sistema, Terminal, ciclos de carga e apps de terceiros.",
    date: "2026-04-02",
    content: `<p>A bateria do seu MacBook degrada com o tempo. Monitorar a saúde ajuda a planejar a substituição.</p><h2>O que significa saúde da bateria</h2><ul><li><strong>Capacidade máxima:</strong> Porcentagem da capacidade original. Apple considera consumida abaixo de 80%.</li><li><strong>Ciclos de carga:</strong> A maioria dos MacBooks é projetada para 1.000 ciclos.</li></ul><h2>Método 1: Ajustes do Sistema</h2><p>Menu Apple > Ajustes do Sistema > Bateria > ⓘ ao lado de Condição da bateria.</p><h2>Método 2: Terminal</h2><p><strong>system_profiler SPPowerDataType</strong></p><h2>Método 3: Apps de barra de menus</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a> mostra saúde, ciclos, watts e tempo restante na barra de menus.</p><h2>Prolongar a vida da bateria</h2><ul><li>Usar Carregamento otimizado.</li><li>Evitar temperaturas extremas.</li><li>Manter carga entre 20% e 80%.</li></ul><h2>Resumo</h2><p>Verifique a saúde da bateria com ferramentas da Apple ou <a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>. Métricas-chave: capacidade máxima e ciclos de carga.</p>`,
  },
};
