import type { ArticleSet } from "./index";

export const zhArticles: ArticleSet = {
  "how-to-check-cpu-temperature-on-mac": { slug: "how-to-check-cpu-temperature-on-mac", title: "如何查看Mac的CPU温度（2026指南）", description: "了解监控Mac处理器温度的所有方法——从终端命令到第三方应用。涵盖Apple Silicon和Intel。", date: "2026-04-02", content: `<p>Mac的CPU温度是需要关注的最重要指标之一，尤其是在进行视频编辑、软件开发或游戏时。过热的处理器会导致热节流、性能降低和硬件寿命缩短。</p><h2>为什么CPU温度很重要</h2><p>现代处理器设计在特定的热包络内运行。当CPU超过此包络时，系统会降低时钟速度——即<strong>热节流</strong>。</p><h2>正常温度范围</h2><ul><li><strong>空闲：</strong>Apple Silicon: 35–55°C，Intel: 40–60°C。</li><li><strong>中等负载：</strong>Apple Silicon: 60–80°C，Intel: 65–85°C。</li><li><strong>高负载：</strong>Apple Silicon: 80–100°C，Intel: 85–100°C。</li></ul><h2>方法1：终端powermetrics</h2><p><strong>sudo powermetrics --samplers smc -i 1000 -n 1</strong></p><h2>方法2：菜单栏应用</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>在菜单栏的紧凑小部件中显示CPU温度、GPU温度、传感器读数、风扇速度、CPU负载、内存压力、网络速度和电池健康状况。</p><h2>Mac过热时怎么办</h2><ol><li>检查活动监视器。</li><li>关闭不必要的标签和应用。</li><li>确保良好的空气流通。</li><li>清洁风扇。</li></ol><h2>总结</h2><p>使用<a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>等工具定期监控，有助于早期发现问题并延长硬件寿命。</p>` },
  "what-is-memory-pressure-on-mac": { slug: "what-is-memory-pressure-on-mac", title: "Mac上的内存压力是什么以及为什么重要", description: "了解macOS内存压力——绿色、黄色和红色级别——以及Mac如何通过压缩、固定和应用内存管理RAM。", date: "2026-04-02", content: `<p>内存压力是反映Mac物理RAM承受多少需求的综合指标。</p><h2>内存压力解释</h2><ul><li><strong>绿色：</strong>充足的可用内存。理想状态。</li><li><strong>黄色：</strong>内存资源受限。</li><li><strong>红色：</strong>严重压力。大量使用交换空间。</li></ul><h2>菜单栏应用监控</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>在菜单栏中直接以颜色编码的指示器显示内存压力。</p><h2>你实际需要多少RAM</h2><ul><li><strong>8 GB：</strong>轻度使用。</li><li><strong>16 GB：</strong>大多数用户的最佳选择。</li><li><strong>24–32 GB：</strong>专业工作流程。</li></ul><h2>总结</h2><p>内存压力是macOS上最重要的内存指标。<a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>等工具让监控变得简单。</p>` },
  "best-system-monitor-apps-for-mac": { slug: "best-system-monitor-apps-for-mac", title: "2026年Mac最佳系统监控应用完整对比", description: "对比Mac顶级系统监控应用——iStat Menus、Stats、MenuMeters、TG Pro和Pulse。功能、价格和优缺点。", date: "2026-04-02", content: `<p>在这份全面对比中，我们评估了2026年最受欢迎的五款Mac系统监控应用。</p><h2>iStat Menus</h2><p>最成熟的监控应用。深度自定义。$11.99。</p><h2>Stats</h2><p>免费开源。</p><h2>Pulse</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>在Mac App Store以$5.99提供现代SwiftUI界面的全面覆盖。</p><table><tr><th>功能</th><th>iStat Menus</th><th>Stats</th><th>MenuMeters</th><th>TG Pro</th><th>Pulse</th></tr><tr><td>CPU</td><td>是</td><td>是</td><td>是</td><td>基础</td><td>是</td></tr><tr><td>内存压力</td><td>是</td><td>是</td><td>基础</td><td>否</td><td>是</td></tr><tr><td>Mac App Store</td><td>否</td><td>否</td><td>否</td><td>否</td><td>是</td></tr><tr><td>价格</td><td>$11.99</td><td>免费</td><td>免费</td><td>$20</td><td>$5.99</td></tr></table><h2>总结</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>提供最佳性价比。</p>` },
  "how-to-monitor-network-speed-on-mac": { slug: "how-to-monitor-network-speed-on-mac", title: "如何在Mac上实时监控网络速度", description: "学习使用活动监视器、终端和菜单栏应用追踪Mac的上传和下载速度。", date: "2026-04-02", content: `<p>了解Mac的实时网络速度对下载、视频通话和故障排除非常有用。</p><h2>活动监视器</h2><p>网络标签：接收数据/秒和发送数据/秒。</p><h2>菜单栏应用</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>在菜单栏实时显示上传/下载速度。</p><h2>故障排除</h2><ol><li>运行速度测试。</li><li>检查Wi-Fi信号。</li><li>用<a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>识别带宽消耗者。</li><li>切换到以太网。</li><li>更改DNS服务器。</li></ol><h2>总结</h2><p>实时监控有助于理解连接状况并高效解决问题。</p>` },
  "mac-running-slow-how-to-fix": { slug: "mac-running-slow-how-to-fix", title: "Mac运行缓慢？如何诊断和修复性能问题", description: "系统化指南，找出Mac缓慢的原因。学习区分CPU、内存和磁盘瓶颈。", date: "2026-04-02", content: `<p>Mac缓慢可能有多种不同原因。准确的诊断至关重要。</p><h2>识别瓶颈类型</h2><ul><li><strong>CPU：</strong>处理器满载。</li><li><strong>内存：</strong>RAM不足。</li><li><strong>磁盘：</strong>存储几乎满了。</li></ul><h2>菜单栏监控</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>始终保持关键指标可见。</p><h2>总结</h2><p>使用活动监视器和<a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>进行诊断和持续监控。</p>` },
  "how-to-check-battery-health-on-mac": { slug: "how-to-check-battery-health-on-mac", title: "如何检查MacBook电池健康状况：完整指南", description: "检查MacBook电池健康的所有方法——系统设置、终端、充电周期和第三方应用。", date: "2026-04-02", content: `<p>MacBook的电池会随时间退化。监控健康状况有助于规划更换。</p><h2>电池健康的含义</h2><ul><li><strong>最大容量：</strong>原始容量的百分比。Apple认为低于80%即为耗尽。</li><li><strong>充电周期：</strong>大多数MacBook设计为1,000个周期。</li></ul><h2>方法1：系统设置</h2><p>Apple菜单 > 系统设置 > 电池 > 电池健康旁的ⓘ。</p><h2>方法2：终端</h2><p><strong>system_profiler SPPowerDataType</strong></p><h2>方法3：菜单栏应用</h2><p><a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>在菜单栏显示电池健康、周期数、功率和剩余时间。</p><h2>延长电池寿命</h2><ul><li>使用优化的电池充电。</li><li>避免极端温度。</li><li>保持充电在20%到80%之间。</li></ul><h2>总结</h2><p>用<a href="https://apps.apple.com/app/pulse-system-monitor/id6744194761">Pulse</a>检查电池健康。关键指标：最大容量和充电周期数。</p>` },
};
