export const metadata = {
  title: "Terms of Service — Esotherik Apps",
  description:
    "Terms of service for all Esotherik spiritual and entertainment apps by Eduard Bruch.",
};

export default function EsotherikTerms() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-20 text-neutral-200">
      <h1 className="mb-4 text-4xl font-bold text-white">Terms of Service</h1>
      <p className="mb-2 text-lg text-neutral-300">Esotherik Apps</p>
      <p className="mb-10 text-sm text-neutral-500">
        Last updated: February 17, 2026
      </p>

      <p className="mb-6">
        These Terms of Service (&quot;Terms&quot;) govern your use of the
        spiritual and entertainment applications published under the Esotherik
        brand by Eduard Bruch (collectively, &quot;the Apps&quot;). By
        downloading, installing, or using any of the Apps, you agree to these
        Terms.
      </p>

      {/* 1. Entertainment Disclaimer */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        1. Entertainment Disclaimer
      </h2>
      <p className="mb-6 border-l-4 border-indigo-500 pl-4 text-neutral-100">
        All content in the Apps — including but not limited to tarot readings,
        horoscope interpretations, numerology reports, aura analyses, palm
        readings, birth chart interpretations, and all other spiritual or
        esoteric content — is provided for{" "}
        <strong>
          entertainment and spiritual exploration purposes only
        </strong>
        . It does not constitute medical, health, psychological, legal, or
        financial advice. You should not make important life decisions based
        solely on content provided by the Apps. Always consult qualified
        professionals for medical, legal, financial, or psychological matters.
      </p>

      {/* 2. Subscriptions */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        2. Subscriptions and Payments
      </h2>
      <p className="mb-4">
        Some Apps offer premium features through auto-renewable subscriptions.
      </p>
      <ul className="mb-6 list-disc pl-6 space-y-2">
        <li>
          Payment will be charged to your Apple ID account at confirmation of
          purchase.
        </li>
        <li>
          Subscription automatically renews unless canceled at least 24 hours
          before the end of the current period.
        </li>
        <li>
          Your account will be charged for renewal within 24 hours prior to the
          end of the current period at the rate of the selected plan.
        </li>
        <li>
          You can manage and cancel your subscriptions by going to your account
          settings on the App Store after purchase.
        </li>
        <li>
          Any unused portion of a free trial period, if offered, will be
          forfeited when you purchase a subscription.
        </li>
      </ul>

      {/* 3. Intellectual Property */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        3. Intellectual Property
      </h2>
      <p className="mb-6">
        All content, designs, graphics, text, artwork, and software in the Apps
        are the intellectual property of Eduard Bruch or their respective
        licensors and are protected by copyright and other intellectual property
        laws. You may not reproduce, distribute, modify, or create derivative
        works from any content in the Apps without prior written consent.
      </p>

      {/* 4. User Conduct */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        4. User Conduct
      </h2>
      <p className="mb-6">
        You agree to use the Apps only for lawful purposes and in accordance
        with these Terms. You may not use the Apps in any manner that could
        damage, disable, overburden, or impair the service.
      </p>

      {/* 5. Limitation of Liability */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        5. Limitation of Liability
      </h2>
      <p className="mb-6">
        To the maximum extent permitted by applicable law, Eduard Bruch shall
        not be liable for any indirect, incidental, special, consequential, or
        punitive damages, or any loss of profits or revenues, whether incurred
        directly or indirectly, or any loss of data, use, goodwill, or other
        intangible losses, resulting from (a) your use of or inability to use
        the Apps; (b) any content obtained from the Apps; or (c) unauthorized
        access to or alteration of your data. This limitation applies to
        entertainment content generated by the Apps, which should not be relied
        upon for important decisions.
      </p>

      {/* 6. No Warranty */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        6. Disclaimer of Warranties
      </h2>
      <p className="mb-6">
        The Apps are provided &quot;as is&quot; and &quot;as available&quot;
        without warranties of any kind, either express or implied, including but
        not limited to implied warranties of merchantability, fitness for a
        particular purpose, and non-infringement. We do not warrant that the
        Apps will be uninterrupted, secure, or error-free.
      </p>

      {/* 7. Governing Law */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        7. Governing Law
      </h2>
      <p className="mb-6">
        These Terms are governed by the laws of the Federal Republic of Germany.
        If you are a consumer within the European Union, you also enjoy the
        protection of the mandatory provisions of consumer protection law in
        your country of residence. The place of jurisdiction is Hamburg, Germany,
        except where mandatory consumer protection law provides otherwise.
      </p>

      {/* 8. Changes */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        8. Changes to These Terms
      </h2>
      <p className="mb-6">
        We may update these Terms from time to time. Continued use of the Apps
        after changes constitutes acceptance of the updated Terms.
      </p>

      {/* 9. Contact */}
      <h2 className="mb-3 mt-10 text-xl font-semibold text-white">
        9. Contact
      </h2>
      <p>
        For questions about these Terms, contact:{" "}
        <a
          href="mailto:support@eduardbruch.com"
          className="text-indigo-400 underline"
        >
          support@eduardbruch.com
        </a>
      </p>
    </main>
  );
}
